### PR TITLE
Test all REDCapR and REDCapTidieR databases

### PR DESCRIPTION
**Pull request by rsh52**
# Description

This PR adds some additional testing to our `utility/` and `refresh.R` methods for CRAN preparation and submission.

`source`ing `test_creds.R` will run all REDCapR databases (minus a few that were identified as not being compatible with REDCapTidieR for acceptable reasons, see script comments) as well as all REDCapTidieR test databases and sample databases of interest to CGT Informatics.

The output is saved as a list to `microbenchmark_results.RDS` with the date stamp. 

## Potential Improvements

- Dynamically name `microbenchmark` list elements with more informative names. For now, errors will return indexes which is good enough for identifying problem APIs.
- Improve time. While none of the calls themselves were very long, running all of them at once through `microbenchmark` takes ~10 minutes.

### CODE REVIEW

**Review by ezraporter — APPROVED** [review]
Looks good! My only comment is that it might be better to output the results as `csv` rather than `rds` so that it shows up nicely in version control. Also might be good enough to keep a single output file and let GH keep the history. Could go either way.

**Comment by skadauke** [comment]
I like both of Ezra's suggestions 🙂
________________________________
From: Ezra Porter ***@***.***>
Sent: Thursday, March 16, 2023 4:20 PM
To: CHOP-CGTInformatics/REDCapTidieR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External]Re: [CHOP-CGTInformatics/REDCapTidieR] Test all REDCapR and REDCapTidieR databases (PR #140)


@ezraporter approved this pull request.

Looks good! My only comment is that it might be better to output the results as csv rather than rds so that it shows up nicely in version control. Also might be good enough to keep a single output file and let GH keep the history. Could go either way.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTInformatics%2FREDCapTidieR%2Fpull%2F140%23pullrequestreview-1344653628&data=05%7C01%7Ckadaukes%40chop.edu%7Ce82486b9105146f943cf08db265bdcb8%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638145948208549228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ocHwIG9JdVMptQc2S8eXbvuDyfl%2BOe2HnaP7oRfbHRk%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWV4F5FWRKMRXM7YKZ3W4NYYBANCNFSM6AAAAAAV5UYOCY&data=05%7C01%7Ckadaukes%40chop.edu%7Ce82486b9105146f943cf08db265bdcb8%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638145948208549228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z9E5%2BEf%2BxCxh1NUQJgWiUD1cFjPkRMDGYHrnWHXdRHw%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by rsh52** [comment]
Is there a good way to do this with `microbenchmark`'s output? It comes out as a `microbenchmark` object and unnesting the list elements looks kind of ugly and less informative:

image

**Comment by skadauke** [comment]
Maybe summary()?
________________________________
From: Rich Hanna ***@***.***>
Sent: Thursday, March 16, 2023 4:27 PM
To: CHOP-CGTInformatics/REDCapTidieR ***@***.***>
Cc: Stephan Kadauke ***@***.***>; Comment ***@***.***>
Subject: [External]Re: [CHOP-CGTInformatics/REDCapTidieR] Test all REDCapR and REDCapTidieR databases (PR #140)


Is there a good way to do this with microbenchmark's output? It comes out as a microbenchmark object and unnesting the list elements looks kind of ugly and less informative:

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F38384694%2F225744715-a6ccd025-7d74-4acf-b0b7-aabc64edd329.png&data=05%7C01%7Ckadaukes%40chop.edu%7C0108128a1ea94a31d10408db265ce0fe%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638145952584808066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D46bK1p4FL%2F%2FaGgvRSsfsd991zBr%2FAcCUoT%2FRNY6e3w%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCHOP-CGTInformatics%2FREDCapTidieR%2Fpull%2F140%23issuecomment-1472692624&data=05%7C01%7Ckadaukes%40chop.edu%7C0108128a1ea94a31d10408db265ce0fe%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638145952584808066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FPjX8lrzUka4QJiX3Gm%2BmXuUGBKV93sWAuxoqh%2BLIpw%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTGHWRLW5BRVIE5BNFZVG3W4NZTLANCNFSM6AAAAAAV5UYOCY&data=05%7C01%7Ckadaukes%40chop.edu%7C0108128a1ea94a31d10408db265ce0fe%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638145952584808066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yd7HuGCguFbSI2M9LC8yG0M2iQ38rf34ogLu9PSCxnM%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by rsh52** [comment]
Look good now? @ezraporter

**Pull request merged**
