### PR TITLE
Survey bug fix

### PR DESCRIPTION
**Pull request by rsh52**
# Description
This PR resolves a newly identified bug involving survey REDCap databases and allows for some aesthetic cleanup to make working with surveys easier and streamlined.

It was found that `redcap_survey_identifer` was being pulled into all instruments regardless of the existence of actual survey variables or whether the form in question was a survey-enabled one.

It was also determined that since survey timestamp variables exist in all survey-enabled forms as `*_timestamp`, it makes more sense to handle these variables in the same way as `form_status_complete` and give them a standard name (`redcap_survey_timestamp`). 

To accommodate these changes, mocks were remade and the affected areas of hard-coding in `make_labelled` have been updated.

# Proposed Changes 
List changes below in bullet format:

- Apply logic for `*_timestamp` similar to standard naming of `form_status_complete`
- Add conditional logic to look for `*_timestamp` _before_ including `select`ion of `redcap_survey_identifier`, effectively dropping it from forms where it does not apply
- Updated `labelled.R` to look for `redcap_survey_timestamp` instead of `survey_timestamp`
- Re-write affected mocks
- Update `testthat` tests accordingly
   - To note I did a complicated `purrr` check to make sure that both of these variables do not pop up in any of our other forms, but know how that's frowned upon so I did away with it 😄 More of a sanity check.

### Issue Addressed
**No Issue Written, we're going right for the PR!**

### PR Checklist
Before submitting this PR, please check and verify below that the submission meets the below criteria:

- [x] New/revised functions have associated tests
- [x] New/revised functions that update downstream outputs have associated static testing files (`.RDS`) updated under `inst/testdata/create_test_data.R`
- [x] New tests that make API calls use `httptest::with_mock_api` and any new mocks were added to `tests/testthat/fixtures/create_httptest_mocks.R`
- [x] New/revised functions use appropriate naming conventions
- [x] New/revised functions don't repeat code
- [x] Code changes are less than **250** lines total
- [NA] Issues linked to the PR using [GitHub's list of keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] The appropriate reviewer is assigned to the PR
- [x] The appropriate developers are assigned to the PR

# Code Review
This section to be used by the reviewer and developers during Code Review after PR submission

### Code Review Checklist

- [ ] I checked that new files follow naming conventions and are in the right place
- [ ] I checked that documentation is complete, clear, and without typos
- [ ] I added/edited comments to explain "why" not "how"
- [ ] I checked that all new variable and function names follow naming conventions
- [ ] I checked that new tests have been written for key business logic and/or bugs that this PR fixes
- [ ] I checked that new tests address important edge cases

### CODE REVIEW

**Review by skadauke — COMMENTED** [review]
This looks good, but I'm confused about 2 things

1) How come mocks needed to be updated? I don't think we changed anything on the backend? And why were 4 CSV files deleted during that mock update? Seems like it didn't break anything...
2) Your Proposed Changes mentions rewriting mocks and and removing a `purrr` check but I don't see this in the file changes?

**Comment by rsh52** [comment]
> This looks good, but I'm confused about 2 things
> 
> 1. How come mocks needed to be updated? I don't think we changed anything on the backend? And why were 4 CSV files deleted during that mock update? Seems like it didn't break anything...

I'm not positive, but I think they needed to be rewritten because of the result of `export_surveys` and the downstream final output. Technically the output from the mock changed with this, even if it was only for `redcap_survey_identifier` and `redcap_survey_timestamp`. I'm unsure why only deletions happened and why it was 4 of them, but I followed the steps for creating the mocks in the `create-http-test-mock.R` file after deleting the institution folder per Ezra's recommendation.

> 2. Your Proposed Changes mentions rewriting mocks and and removing a `purrr` check but I don't see this in the file changes?

Yea, I got rid of it but did it for my own sanity check. This is what it looked like as an addition to [`test-import_redcap.R` lines 361+](https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/1273bf98a13d2be061b40366e252bdba6cb93558/tests/testthat/test-import_redcap.R#L361-L380):

```r
  # Check that other forms do not contain survey variables
  # First compile all variable names from all non-survey instruments
  non_survey_form_names <- purrr::map(.x = out |> extract_tibbles(tbls = !contains("survey")),
             .f = ~ names(.x))

  # Next create boolean to check for survey fields
  survey_var_check <- purrr::map(non_survey_form_names, ~any(c("redcap_survey_timestamp", "redcap_survey_identifier") %in% .x))
  
  # Last, run expectation that none exist
  expect_false(all(survey_var_check))
```
I can re-implement if we want, but it definitely doesn't jive with keeping tests super easy to read.

**Comment by skadauke** [comment]
> > This looks good, but I'm confused about 2 things
> > 
> > 1. How come mocks needed to be updated? I don't think we changed anything on the backend? And why were 4 CSV files deleted during that mock update? Seems like it didn't break anything...
> 
> I'm not positive, but I think they needed to be rewritten because of the result of `export_surveys` and the downstream final output. Technically the output from the mock changed with this, even if it was only for `redcap_survey_identifier` and `redcap_survey_timestamp`. I'm unsure why only deletions happened and why it was 4 of them, but I followed the steps for creating the mocks in the `create-http-test-mock.R` file after deleting the institution folder per Ezra's recommendation.

Since none of the actual API calls changed, I would have expected the mocks to stay the same. Anyhow, all the tests pass so I'm OK with that. Most likely the 4 CSVs are left over from some old stuff. 

> > 2. Your Proposed Changes mentions rewriting mocks and and removing a `purrr` check but I don't see this in the file changes?
> 
> Yea, I got rid of it but did it for my own sanity check. This is what it looked like as an addition to [`test-import_redcap.R` lines 361+](https://github.com/CHOP-CGTInformatics/REDCapTidieR/blob/1273bf98a13d2be061b40366e252bdba6cb93558/tests/testthat/test-import_redcap.R#L361-L380):
> 
> ```r
>   # Check that other forms do not contain survey variables
>   # First compile all variable names from all non-survey instruments
>   non_survey_form_names <- purrr::map(.x = out |> extract_tibbles(tbls = !contains("survey")),
>              .f = ~ names(.x))
> 
>   # Next create boolean to check for survey fields
>   survey_var_check <- purrr::map(non_survey_form_names, ~any(c("redcap_survey_timestamp", "redcap_survey_identifier") %in% .x))
>   
>   # Last, run expectation that none exist
>   expect_false(all(survey_var_check))
> ```
> 
> I can re-implement if we want, but it definitely doesn't jive with keeping tests super easy to read.

Ah! Got it. I misunderstood - thought you'd removed some existing code but you really just wrote some code and then chose not to include it :)

**Review by skadauke — COMMENTED** [review]
Looks good to me!

**Review by skadauke — APPROVED** [review]

**Pull request merged**
