### PR TITLE
list_select Function Implementation

### PR DESCRIPTION
**Pull request by rsh52**
# Description
This PR introduced a very low-level function that we've found useful in working with the CGTTrialsReporter. A typical workflow we found was to use `extract_tibbles()` on a REDCap supertibble and then select specific named elements from that list output for our analytic objects. This has the additional benefit

A typical workflow, as documented in the roxygen example, is: 

```r
my_list <- extract_tibbles(superheroes_supertbl)
list_select(my_list, starts_with("hero"))
```

Open to name and param suggestions, additional checks, behavior modifications, etc. I originally wanted to call this `supertibble_select()`, but this doesn't really select from the supertibble. If anything `extract_tibbles()` already achieves this.

Currently if users make a tidyselection and nothing is returned, an empty named list is returned. But if they hard code a table to search for and it doesn't exist and helpful error is returned. Wasn't sure if both should error instead.

# Proposed Changes 
List changes below in bullet format:

- Introduce `list_select()` function
- Add tests
- Add to pkgdown

### PR Checklist
Before submitting this PR, please check and verify below that the submission meets the below criteria:

- [x] New/revised functions have associated tests
- [NA] New/revised functions that update downstream outputs have associated static testing files (`.RDS`) updated under `inst/testdata/create_test_data.R`
- [x] New/revised functions use appropriate naming conventions
- [x] New/revised functions don't repeat code
- [x] Code changes are less than **250** lines total
- [NA] Issues linked to the PR using [GitHub's list of keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] The appropriate reviewer is assigned to the PR
- [x] The appropriate developers are assigned to the PR
- [ ] Pre-release package version incremented using `usethis::use_version()`

# Code Review
This section to be used by the reviewer and developers during Code Review after PR submission

### Code Review Checklist

- [ ] I checked that new files follow naming conventions and are in the right place
- [ ] I checked that documentation is complete, clear, and without typos
- [ ] I added/edited comments to explain "why" not "how"
- [ ] I checked that all new variable and function names follow naming conventions
- [ ] I checked that new tests have been written for key business logic and/or bugs that this PR fixes
- [ ] I checked that new tests address important edge cases

### CODE REVIEW

**Review by ezraporter — COMMENTED** [review]
Code is obviously fine! My comments are about the API.

Internally we've used a `list_select`-like function because we've tended to start with:

```r
data_all <- extract_tibbles(supertbl)
```

Is that really what we want users to do? What's the point of this intermediate named list object when you can just do:

```r
extract_tibbles(supertbl, starts_with("tbl"))
```

It feels to me like we should just be encouraging users to do operations on the supertibble.

**Comment by rsh52** [comment]
Yea, fair enough. Personally fine with closing this if we don't think the value is really there, it didn't take much time to put together.

**Comment by ezraporter** [comment]
Yeah my opinion is that the value isn't there for this but there is value in a more comprehensive set of functions that allows you to select from and manipulate the supertibble

**Comment by rsh52** [comment]
Say no more 🫡

**Pull request closed without merging**
